---
title       : TeamMentor
subtitle    : This is simple presentation
author      : Rishi Gupta
job         : Mentor
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
url         :
  lib: ../../libraries
  assets: ../../assets
  
---

## What to Study

- There are vaious courses in the courser.org
- Identify your areas of interest
- Search in coursera.org or udacity whether any such curriculum is available
- In case not search in the youtube for the playlist

---

## The Big Plan

- See how many subjects are there in the curriculum
- See how many hours you could spend time on study other the projects your are working upon
- Make a timeline and adhere to it properly

---

## Resources
- There are various books available in the market / online on the subjects you are trying to understand
- Download them and try to understand the basic concepts

---
## Learning and Application

- Once subject is understood see whether you could work upon some freelancer project on your own
- This will give you clarity on where you stand
- Always try to get the hands-on experience on the subject
- For example the following r code helps in loading the data into memory
```{r}
library(packagename)
```

---
## Create Benchmark
- Apply for certifications in case you are not able to find any project
- This could be used as an add on in your profile

---

Thanks!
